version: 2.1

orbs:
  golang: cci-orb/golang@volatile
  codecov: codecov/codecov@volatile

jobs:
  test:
    parameters:
      go-version:
        type: string
    executor:
      name: golang/linux
      version: "<< parameters.go-version >>"
    working_directory: /go/src/go.lsp.dev/protocol
    resource_class: large
    parallelism: 3
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Test and collect coverages
          environment:
            # https://github.com/gotestyourself/gotestsum#format
            GOTESTSUM_FORMAT: standard-verbose
            # https://github.com/gotestyourself/gotestsum#junit-xml
            GOTESTSUM_JUNITFILE: /tmp/test-results/tests.xml
            # https://github.com/gotestyourself/gotestsum#finding-and-skipping-slow-tests
            GOTESTSUM_JSONFILE: /tmp/test-results/tests.json
          command: |
            mkdir -p /tmp/artifacts /tmp/test-results
            make $(circleci tests split .circleci/coverage-targets)
      - codecov/upload:
          file: "coverage.out"
          flags: $(if [ $CIRCLE_NODE_INDEX == 0 ]; then echo "json"; elif [ $CIRCLE_NODE_INDEX == 1 ]; then echo "gojay"; else echo "gojson"; fi)
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/test-results

  lint:
    parameters:
      go-version:
        type: string
    executor:
      name: golang/linux
      version: "<< parameters.go-version >>"
    working_directory: /go/src/go.lsp.dev/protocol
    resource_class: large
    parallelism: 3
    steps:
      - checkout
      - golang/gomod
      - run:
          name: Run lint for sources
          command: |
            make lint GO_LINT_FLAGS=$(circleci tests split .circleci/lint-buildtags)

workflows:
  version: 2
  workflows:
    jobs:
      - test:
          context: org-global
          matrix:
            parameters:
              go-version: ["1.15-buster", "1.16-rc-buster"]
      - lint:
          context: org-global
          matrix:
            parameters:
              go-version: ["1.15-buster", "1.16-rc-buster"]
